/* CSV is untrusted content. Keep ranking pure and render names as text. */
(function(root){
'use strict';
function parseCSV(text){let rows=[],row=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++;}else quoted=!quoted;}else if(c===','&&!quoted){row.push(cell);cell='';}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cell);if(row.some(Boolean))rows.push(row);row=[];cell='';}else cell+=c;}row.push(cell);if(row.some(Boolean))rows.push(row);const header=(rows.shift()||[]).map(v=>v.replace(/^\uFEFF/,'').trim());return rows.map(values=>Object.fromEntries(header.map((key,i)=>[key,values[i]||''])));}
function rank(rows){const seen=new Set();return rows.filter(r=>{const ok=/^(true|1)$/i.test(String(r.completed))&&r.course_version==='rgc-arcade-v2'&&Number(r.distance_m)===8000&&Number.isFinite(+r.gold_bolts)&&+r.gold_bolts>=0&&Number.isFinite(+r.time_seconds)&&+r.time_seconds>0&&r.display_name&&r.run_id&&!seen.has(r.run_id);if(ok)seen.add(r.run_id);return ok;}).sort((a,b)=>+b.gold_bolts-+a.gold_bolts||+a.time_seconds-+b.time_seconds||String(a.run_id).localeCompare(String(b.run_id))).slice(0,5);}
function aura(r){if(+r.gold_bolts>=500)return 'BOLT SOVEREIGN';if(+r.hazards_hit===0)return 'UNTOUCHABLE';if(+r.time_seconds<360)return 'PACE PHANTOM';if(+r.juice_remaining<=2)return 'LAST-BAR LEGEND';if(+r.boosts_used>=3)return 'TURBO MENACE';return 'RIVER VALLEY GHOST';}
const clock=t=>`${Math.floor(t/60)}:${(t%60).toFixed(2).padStart(5,'0')}`;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const trophy='<svg class="gold-cup" viewBox="0 0 32 36" role="img" aria-label="First place gold cup"><g fill="#f5ba28" stroke="#272727" stroke-width="2" stroke-linejoin="round"><path d="M8 4H3v6c0 5 4 7 8 7m13-13h5v6c0 5-4 7-8 7" fill="none"/><path d="M8 3h16v9c0 7-5 10-8 10s-8-3-8-10Z"/><path d="M14 22h4v8h-4zM9 30h14v4H9z"/></g></svg>';
function mount({getView,pause}){
 const dialog=document.querySelector('#leaderboard-dialog');let scores=rank(root.MZ_LEADERBOARD||[]),selected=null,shown=false,opener=null;
 function list(){selected=null;dialog.querySelector('.leader-content').innerHTML=`<p class="leader-rule">BOLTS FIRST · TIME BREAKS TIES</p><ol class="leader-list">${Array.from({length:5},(_,i)=>{const r=scores[i];return `<li style="--rank:${i}">${r?`<button data-run="${i}"><span class="rank-number">${i===0?trophy:i+1}</span><span class="leader-name"><b>${esc(r.display_name)}</b><small>${aura(r)}</small></span><span class="leader-score"><b>${Number(r.gold_bolts)} ⚡</b><small>${clock(+r.time_seconds)}</small></span></button>`:`<div class="open-rank"><span class="rank-number">${i+1}</span><b>This could be you.</b></div>`}</li>`;}).join('')}</ol>`;dialog.querySelector('[data-tab=leaders]').setAttribute('aria-pressed','true');dialog.querySelector('[data-tab=runner]').disabled=true;dialog.querySelector('[data-tab=runner]').setAttribute('aria-pressed','false');}
 function detail(index){selected=scores[index];if(!selected)return;const r=selected;dialog.querySelector('.leader-content').innerHTML=`<div class="runner-profile"><span class="aura">${aura(r)}</span><h3>${esc(r.display_name)}</h3><dl>${[['Gold bolts',+r.gold_bolts],['Finish time',clock(+r.time_seconds)],['Avg arcade speed',+r.average_arcade_kmh+' km/h'],['Peak arcade speed',+r.peak_arcade_kmh+' km/h'],['Juice',+r.juice_remaining+'/10'],['Boosts',+r.boosts_used],['Hazards hit',+r.hazards_hit],['Distance','8 km']].map(([k,v])=>`<div><dt>${k}</dt><dd>${esc(v)}</dd></div>`).join('')}</dl></div>`;const tab=dialog.querySelector('[data-tab=runner]');tab.disabled=false;tab.setAttribute('aria-pressed','true');dialog.querySelector('[data-tab=leaders]').setAttribute('aria-pressed','false');tab.focus();}
 function open(auto=false){if(auto&&(shown||!['selection','instructions'].includes(getView())))return;if(dialog.open)return;shown=true;opener=document.activeElement;pause();list();dialog.showModal();}
 dialog.addEventListener('click',e=>{const button=e.target.closest('button');if(!button)return;if(button.hasAttribute('data-run'))detail(+button.dataset.run);if(button.dataset.tab==='leaders')list();if(button.hasAttribute('data-close'))dialog.close();});
 dialog.addEventListener('close',()=>opener?.focus({preventScroll:true}));
 window.addEventListener('message',e=>{if(e.source===window.parent&&e.origin===location.origin&&e.data?.type==='mz-console-enter')open(true);});
 if(window.parent===window)new IntersectionObserver(([e],o)=>{if(e.isIntersecting){open(true);o.disconnect();}},{threshold:.3}).observe(document.querySelector('#console'));
 // Public GitHub updates refresh on each visit. Private/offline repositories use the published snapshot.
 const abort=new AbortController();const timeout=setTimeout(()=>abort.abort(),3500);
 fetch('https://raw.githubusercontent.com/jcreatvz/mz/main/prototypes/geymzkii/results.csv',{cache:'no-store',signal:abort.signal}).then(r=>{if(!r.ok)throw Error('CSV unavailable');return r.text();}).then(text=>{if(!text.startsWith('run_id,'))return;scores=rank(parseCSV(text));if(dialog.open&&!selected)list();}).catch(()=>{}).finally(()=>clearTimeout(timeout));
 return {open};
}
const api={parseCSV,rank,aura,clock,mount};if(typeof module!=='undefined')module.exports=api;else root.MZLeaders=api;
})(typeof window==='undefined'?globalThis:window);
